name: HevaWu's Blog
markdown: kramdown
highlighter: rouge
search : true
future: true

plugins:
  - jemoji

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

category_archive:
  type: liquid
  path: /blog/categories/

tag_archive:
  type: liquid
  path: '/blog/tags/'

comments:
provider: "disqus"
disqus:
    shortname: "he_wu"
default:
    comments: true
