name: HevaWu's Blog
markdown: kramdown
highlighter: rouge
search : true
future: true

plugins:
  - jemoji

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

permalink: /blog/:year/:month/:day/:title

category_archive:
  type: liquid
  path: /blog/categories/

tag_archive:
  type: liquid
  path: '/blog/tags/'
